name: echo_app
description: ECHO - Earthquake Coordination & Help Outreach
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.0
  geolocator: ^12.0.0
  audioplayers: ^6.5.1
  flutter_beep: ^1.0.0
  sound_generator: ^0.0.14
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/whistle.wav
